/**
 * hikma add command
 * Add components to project
 */

import { readFile, writeFile } from 'fs/promises';
import { resolve } from 'path';
import pc from 'picocolors';
import ora from 'ora';

export async function addCommand(
  components: string[],
  options: { all?: boolean; overwrite?: boolean }
) {
  console.log(pc.bold(pc.cyan('📦 Adding components...')));
  console.log();

  // Load CLI config
  const config = await loadCliConfig();
  if (!config) {
    console.log(pc.red('✗ HikmaUI not initialized. Run `hikma init` first.'));
    return;
  }

  // Get components to add
  const componentsToAdd = options.all
    ? getAllComponents()
    : components;

  if (componentsToAdd.length === 0) {
    console.log(pc.yellow('No components specified.'));
    console.log(pc.dim('Usage: hikma add button card modal'));
    console.log(pc.dim('   or: hikma add --all'));
    return;
  }

  const spinner = ora('Installing components...').start();

  try {
    for (const component of componentsToAdd) {
      await addComponent(component, config, options.overwrite);
    }

    spinner.succeed(`Added ${componentsToAdd.length} component(s)!`);
    console.log();
    console.log(pc.green('✓ Components added successfully!'));
    console.log();
    console.log(pc.bold('Components added:'));
    componentsToAdd.forEach(c => console.log(pc.dim(`  - ${c}`)));
    console.log();
  } catch (error) {
    spinner.fail('Failed to add components');
    console.error(pc.red(error instanceof Error ? error.message : 'Unknown error'));
    process.exit(1);
  }
}

async function loadCliConfig() {
  try {
    const configPath = resolve(process.cwd(), 'hikma.json');
    const content = await readFile(configPath, 'utf-8');
    return JSON.parse(content);
  } catch {
    return null;
  }
}

function getAllComponents(): string[] {
  return [
    'button',
    'card',
    'modal',
    'alert',
    'badge',
    'avatar',
    'tooltip',
    'dropdown',
    'tabs',
    'accordion',
    'breadcrumb',
    'pagination',
    'input',
    'select',
    'checkbox',
  ];
}

async function addComponent(
  name: string,
  config: any,
  overwrite?: boolean
) {
  // TODO: Fetch component from registry or local templates
  // For now, just a placeholder
  console.log(pc.dim(`  Adding ${name}...`));

  // Component template would go here
  const componentCode = generateComponentTemplate(name, config.framework);

  const componentPath = resolve(
    process.cwd(),
    config.componentsDir,
    `${name}.tsx`
  );

  await writeFile(componentPath, componentCode, 'utf-8');
}

function generateComponentTemplate(name: string, framework: string): string {
  // Simplified template - will be expanded with actual components
  return `/**
 * ${name.charAt(0).toUpperCase() + name.slice(1)} Component
 * Generated by HikmaUI CLI
 */

export function ${name.charAt(0).toUpperCase() + name.slice(1)}() {
  return (
    <div className="hikma-${name}">
      {/* Component implementation */}
    </div>
  );
}
`;
}
