/**
 * Animation utilities for HikmaUI components.
 * These use HikmaUI's raw CSS classes and custom animations,
 * no external dependencies like Framer Motion.
 */

/**
 * Transition presets for common animations.
 * These classes are generated by HikmaUI's JIT compiler.
 */
export const transitions = {
  // Base transitions
  base: "transition-all duration-200 ease-in-out",
  colors: "transition-colors duration-200 ease-in-out",
  opacity: "transition-opacity duration-150 ease-in-out",
  transform: "transition-transform duration-200 ease-in-out",

  // Speed variants
  fast: "transition-all duration-100 ease-in-out",
  normal: "transition-all duration-200 ease-in-out",
  slow: "transition-all duration-300 ease-in-out",
  slower: "transition-all duration-500 ease-in-out",

  // Easing functions (custom cubic-bezier)
  spring: "transition-all duration-300 cubic-bezier(0.68, -0.55, 0.265, 1.55)",
  smooth: "transition-all duration-200 cubic-bezier(0.4, 0, 0.2, 1)",
  easeOut: "transition-all duration-200 cubic-bezier(0, 0, 0.2, 1)",
  easeIn: "transition-all duration-200 cubic-bezier(0.4, 0, 1, 1)",
  easeInOut: "transition-all duration-200 cubic-bezier(0.4, 0, 0.2, 1)",
} as const;

/**
 * Built-in keyframe animations.
 * These will be added to HikmaUI core as custom animations.
 */
export const animations = {
  // Spinning
  spin: "animate-spin",
  spinSlow: "animate-spin-slow",
  spinFast: "animate-spin-fast",

  // Pulsing
  pulse: "animate-pulse",
  pulseSlow: "animate-pulse-slow",
  pulseFast: "animate-pulse-fast",

  // Bouncing
  bounce: "animate-bounce",
  bounceSubtle: "animate-bounce-subtle",

  // Fading
  fadeIn: "animate-fade-in",
  fadeOut: "animate-fade-out",

  // Sliding
  slideInUp: "animate-slide-in-up",
  slideInDown: "animate-slide-in-down",
  slideInLeft: "animate-slide-in-left",
  slideInRight: "animate-slide-in-right",
  slideOutUp: "animate-slide-out-up",
  slideOutDown: "animate-slide-out-down",
  slideOutLeft: "animate-slide-out-left",
  slideOutRight: "animate-slide-out-right",

  // Scaling
  scaleIn: "animate-scale-in",
  scaleOut: "animate-scale-out",

  // Shake (for errors)
  shake: "animate-shake",

  // Progress/loading
  shimmer: "animate-shimmer",
  progress: "animate-progress",
} as const;

/**
 * Animation duration classes.
 */
export const durations = {
  75: "duration-75",
  100: "duration-100",
  150: "duration-150",
  200: "duration-200",
  300: "duration-300",
  500: "duration-500",
  700: "duration-700",
  1000: "duration-1000",
} as const;

/**
 * Animation delay classes.
 */
export const delays = {
  75: "delay-75",
  100: "delay-100",
  150: "delay-150",
  200: "delay-200",
  300: "delay-300",
  500: "delay-500",
  700: "delay-700",
  1000: "delay-1000",
} as const;

/**
 * Helper to create staggered animations for list items.
 *
 * @param index - Item index
 * @param baseDelay - Base delay in milliseconds
 * @returns Style object with animation delay
 *
 * @example
 * {items.map((item, index) => (
 *   <div style={stagger(index, 50)}>{item}</div>
 * ))}
 */
export function stagger(index: number, baseDelay: number = 100) {
  return {
    animationDelay: `${index * baseDelay}ms`,
  };
}

/**
 * Helper to create spring-based transitions with custom parameters.
 *
 * @param tension - Spring tension (higher = faster)
 * @param friction - Spring friction (higher = less bouncy)
 * @returns Style object with custom cubic-bezier
 *
 * @example
 * <div style={spring(300, 20)}>Content</div>
 */
export function spring(tension: number = 300, friction: number = 20) {
  // Convert spring physics to cubic-bezier approximation
  const w0 = Math.sqrt(tension);
  const zeta = friction / (2 * Math.sqrt(tension));

  const p1 = zeta < 1 ? 0.68 : 0.4;
  const p2 = zeta < 1 ? -0.55 : 0;
  const p3 = zeta < 1 ? 0.265 : 0.2;
  const p4 = zeta < 1 ? 1.55 : 1;

  return {
    transition: `all 300ms cubic-bezier(${p1}, ${p2}, ${p3}, ${p4})`,
  };
}

/**
 * Preset animation configurations for common UI patterns.
 */
export const presets = {
  // Modal/Dialog
  modal: {
    overlay: "animate-fade-in duration-200",
    content: "animate-scale-in duration-200 ease-out",
  },

  // Dropdown/Menu
  dropdown: {
    enter: "animate-slide-in-down duration-150 ease-out",
    exit: "animate-slide-out-up duration-100 ease-in",
  },

  // Toast/Notification
  toast: {
    enter: "animate-slide-in-right duration-200 ease-out",
    exit: "animate-slide-out-right duration-150 ease-in",
  },

  // Tooltip
  tooltip: {
    top: "animate-slide-in-up duration-150 ease-out",
    bottom: "animate-slide-in-down duration-150 ease-out",
    left: "animate-slide-in-left duration-150 ease-out",
    right: "animate-slide-in-right duration-150 ease-out",
  },

  // Accordion
  accordion: {
    expand: "transition-all duration-200 ease-out",
    collapse: "transition-all duration-200 ease-in",
  },

  // Button
  button: {
    hover: "transition-colors duration-150 ease-in-out",
    active: "transition-transform duration-75 ease-in-out",
  },

  // Input
  input: {
    focus: "transition-colors duration-150 ease-in-out",
  },

  // Loading
  loading: {
    spinner: "animate-spin duration-700",
    dots: "animate-pulse duration-1000",
    shimmer: "animate-shimmer duration-1000",
  },
} as const;

/**
 * CSS keyframes to be added to HikmaUI core.
 * These should be added to the core package's animation generator.
 */
export const keyframes = `
@keyframes fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes fade-out {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}

@keyframes slide-in-up {
  from {
    transform: translateY(10px);
    opacity: 0;
  }
  to {
    transform: translateY(0);
    opacity: 1;
  }
}

@keyframes slide-in-down {
  from {
    transform: translateY(-10px);
    opacity: 0;
  }
  to {
    transform: translateY(0);
    opacity: 1;
  }
}

@keyframes slide-in-left {
  from {
    transform: translateX(-10px);
    opacity: 0;
  }
  to {
    transform: translateX(0);
    opacity: 1;
  }
}

@keyframes slide-in-right {
  from {
    transform: translateX(10px);
    opacity: 0;
  }
  to {
    transform: translateX(0);
    opacity: 1;
  }
}

@keyframes slide-out-up {
  from {
    transform: translateY(0);
    opacity: 1;
  }
  to {
    transform: translateY(-10px);
    opacity: 0;
  }
}

@keyframes slide-out-down {
  from {
    transform: translateY(0);
    opacity: 1;
  }
  to {
    transform: translateY(10px);
    opacity: 0;
  }
}

@keyframes slide-out-left {
  from {
    transform: translateX(0);
    opacity: 1;
  }
  to {
    transform: translateX(-10px);
    opacity: 0;
  }
}

@keyframes slide-out-right {
  from {
    transform: translateX(0);
    opacity: 1;
  }
  to {
    transform: translateX(10px);
    opacity: 0;
  }
}

@keyframes scale-in {
  from {
    transform: scale(0.95);
    opacity: 0;
  }
  to {
    transform: scale(1);
    opacity: 1;
  }
}

@keyframes scale-out {
  from {
    transform: scale(1);
    opacity: 1;
  }
  to {
    transform: scale(0.95);
    opacity: 0;
  }
}

@keyframes shake {
  0%, 100% {
    transform: translateX(0);
  }
  10%, 30%, 50%, 70%, 90% {
    transform: translateX(-10px);
  }
  20%, 40%, 60%, 80% {
    transform: translateX(10px);
  }
}

@keyframes shimmer {
  0% {
    background-position: -1000px 0;
  }
  100% {
    background-position: 1000px 0;
  }
}

@keyframes progress {
  0% {
    transform: translateX(-100%);
  }
  100% {
    transform: translateX(100%);
  }
}

@keyframes spin-slow {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}

@keyframes pulse-slow {
  0%, 100% {
    opacity: 1;
  }
  50% {
    opacity: 0.5;
  }
}

@keyframes bounce-subtle {
  0%, 100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-10px);
  }
}
`;
